export const GET_ACCOUNT_PHOTO_URL = 'GET_ACCOUNT_PHOTO_URL';
export const HANDLE_ACCOUNT_PHOTO_FILE_CHANGE = 'HANDLE_ACCOUNT_PHOTO_FILE_CHANGE';
export const START_ACCOUNT_EDIT = 'START_ACCOUNT_EDIT';
export const FINISH_ACCOUNT_EDIT = 'FINISH_ACCOUNT_EDIT';
export const SAVE_USER_ACCOUNT = 'SAVE_USER_ACCOUNT';
