export const IS_ACCOUNT_EDIT_MODE = 'IS_ACCOUNT_EDIT_MODE';
export const ACCOUNT_PHOTO_URL = 'ACCOUNT_PHOTO_URL';
export const ACCOUNT_PHOTO_FILE = 'ACCOUNT_PHOTO_FILE';
export const ACCOUNT_PHOTO_PREVIEW_URL = 'ACCOUNT_PHOTO_PREVIEW_URL';
export const ACCOUNT_DISPLAY_NAME = 'ACCOUNT_DISPLAY_NAME';
