export const UPDATE_ACCOUNT_EDIT_MODE = 'UPDATE_ACCOUNT_EDIT_MODE';
export const UPDATE_ACCOUNT_PHOTO_URL = 'UPDATE_ACCOUNT_PHOTO_URL';
export const UPDATE_ACCOUNT_PHOTO_FILE = 'UPDATE_ACCOUNT_PHOTO_FILE';
export const UPDATE_ACCOUNT_PHOTO_PREVIEW_URL = 'UPDATE_ACCOUNT_PHOTO_PREVIEW_URL';
export const UPDATE_ACCOUNT_DISPLAY_NAME = 'UPDATE_ACCOUNT_DISPLAY_NAME';
export const RESET_ACCOUNT_EDIT_FORM = 'RESET_ACCOUNT_EDIT_FORM';
