export const REQUIREMENTS = 'REQUIREMENTS';
export const SIDE_BAR_VISIBLE = 'SIDE_BAR_VISIBLE';
export const NEW_CARD_VISIBLE = 'NEW_CARD_VISIBLE';
// export const REGISTRATION_VISIBLE = 'REGISTRATION_VISIBLE';
// export const NEW_TASK_VISIBLE = 'NEW_TASK_VISIBLE';
