export const SET_REQUIREMENTS = 'SET_REQUIREMENTS';
export const TOOGLE_SIDEBAR = 'TOOGLE_SIDEBAR';
export const TOOGLE_NEWCARD = 'TOOGLE_NEWCARD';
export const TOOGLE_REGISTRATION = 'TOOGLE_REGISTRATION';
export const TOOGLE_NEWTASK = 'TOOGLE_NEWTASK';

