export const CARDS = 'CARDS';
export const CARDS_LOADING = 'CARDS_LOADING';
export const IS_CARD_CREATION_STARTED = 'IS_CARD_CREATION_STARTED';
export const NEW_CARD_TITLE = 'NEW_CARD_TITLE';
export const NEW_CARD_JIRALINK = 'NEW_CARD_JIRALINK';
export const NEW_CARD_CRNUMBER = 'NEW_CARD_CRNUMBER';
export const NEW_CARD_PROJECT = 'NEW_CARD_PROJECT';

