export const UPDATE_CARDS = 'UPDATE_CARDS';
export const UPDATE_CARDS_LOADING = 'UPDATE_CARDS_LOADING';
export const UPDATE_CARD_CREATION_STARTED = 'UPDATE_CARD_CREATION_STARTED';
export const UPDATE_NEW_CARD_TITLE = 'UPDATE_NEW_CARD_TITLE';
export const RESET_NEW_CARD = 'RESET_NEW_CARD';
export const RESET_CARDS = 'RESET_CARDS';
export const UPDATE_NEW_CARD_COMPLETED = 'UPDATE_NEW_CARD_COMPLETED';
export const UPDATE_NEW_CARD_CRNUMBER = 'UPDATE_NEW_CARD_CRNUMBER';

