export const TASKS = 'TASKS';
export const TASKS_LOADING = 'TASKS_LOADING';
export const IS_TASK_CREATION_STARTED = 'IS_TASK_CREATION_STARTED';
export const NEW_TASK_TITLE = 'NEW_TASK_TITLE';
export const NEW_TASK_DESCRIPTION = 'NEW_TASK_DESCRIPTION';
export const NEW_TASK_COMPLETED = 'NEW_TASK_COMPLETED';
export const NEW_TASK_EFFORT = 'NEW_TASK_EFFORT';
export const NEW_TASK_ESTIMATOR = 'NEW_TASK_ESTIMATOR';

